#!/usr/bin/env python3
"""
AI Research & Analysis Platform Demo

This demo showcases the full functionality of the Swarms framework by creating
a comprehensive research platform with multiple specialized agents working together.

Features demonstrated:
- Multiple agent types (Agent, ToolAgent, Worker)
- Sequential and concurrent workflows
- Agent specialization and collaboration
- File operations and document processing
- Error handling and fallback mechanisms
- Interactive CLI interface
- Local and cloud LLM integration
"""

import os
import sys
import json
import time
from pathlib import Path
from typing import List, Dict, Any, Optional
from datetime import datetime
import asyncio

# Add the swarms package to path if running from repo
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from swarms import Agent, OpenAIChat, SequentialWorkflow, ConcurrentWorkflow, Task
    from swarms.structs import SwarmNetwork
    from swarms.utils.loguru_logger import logger
    from swarms.tools import tool
except ImportError as e:
    print(f"Import error: {e}")
    print("Please ensure swarms is properly installed: pip install -e .")
    sys.exit(1)

from dotenv import load_dotenv

# Load environment variables
load_dotenv()

class MockLLM:
    """Mock LLM for demonstration when API keys are not available"""
    
    def __init__(self, name: str = "MockLLM"):
        self.name = name
        self.call_count = 0
    
    def __call__(self, prompt: str, *args, **kwargs) -> str:
        self.call_count += 1
        return self._generate_mock_response(prompt)
    
    def _generate_mock_response(self, prompt: str) -> str:
        """Generate contextual mock responses based on prompt content"""
        prompt_lower = prompt.lower()
        
        if "research" in prompt_lower and "climate change" in prompt_lower:
            return f"""Based on current scientific literature, climate change represents one of the most pressing challenges of our time. Key findings include:

1. **Temperature Rise**: Global average temperatures have increased by approximately 1.1°C since pre-industrial times
2. **Attribution**: Human activities, particularly greenhouse gas emissions, are the primary driver
3. **Impacts**: Observable effects include rising sea levels, extreme weather events, and ecosystem disruption
4. **Solutions**: Transition to renewable energy, carbon capture technologies, and international cooperation

Sources: IPCC AR6 Report, Nature Climate Change journal articles, NASA climate data.

[Generated by {self.name} - Call #{self.call_count}]"""

        elif "analyze" in prompt_lower or "fact" in prompt_lower:
            return f"""Analysis Summary:
✓ Claims verified against peer-reviewed sources
✓ Data points cross-referenced with authoritative databases
✓ Methodology reviewed for scientific rigor
✓ Conclusions supported by evidence

Confidence Level: High (85%)
Reliability Score: 4.2/5.0

[Generated by {self.name} - Call #{self.call_count}]"""

        elif "summarize" in prompt_lower or "executive" in prompt_lower:
            return f"""EXECUTIVE SUMMARY

Research Topic: Climate Change Impact Assessment
Analysis Period: Current scientific consensus (2020-2024)

KEY FINDINGS:
• Phenomenon confirmed through multiple independent studies
• Significant environmental and economic implications identified
• Urgent action required based on current trajectory
• Multiple viable solution pathways available

RECOMMENDATIONS:
1. Implement evidence-based policy measures
2. Increase investment in sustainable technologies
3. Enhance international collaboration frameworks
4. Develop adaptive strategies for affected regions

Next Steps: Detailed implementation planning and stakeholder engagement.

[Generated by {self.name} - Call #{self.call_count}]"""

        elif "write" in prompt_lower or "create" in prompt_lower:
            return f"""Research Report: {datetime.now().strftime('%Y-%m-%d')}

This comprehensive analysis examines the current state of knowledge regarding the research topic. Through systematic review of available literature and data sources, we have identified key trends, challenges, and opportunities.

Our methodology included multi-source verification, expert consultation, and quantitative analysis where applicable. The findings presented here represent the most current understanding of the subject matter.

[Generated by {self.name} - Call #{self.call_count}]"""

        else:
            return f"I understand you're asking about: {prompt[:100]}...\n\nBased on my analysis, I can provide insights and recommendations. However, this is a demonstration response from {self.name} (call #{self.call_count}). For production use, please configure appropriate LLM API keys."


def setup_llm() -> Any:
    """Setup LLM with fallback to mock if API key not available"""
    api_key = os.getenv("OPENAI_API_KEY")
    
    if api_key:
        try:
            llm = OpenAIChat(
                openai_api_key=api_key,
                model_name="gpt-3.5-turbo",
                temperature=0.7,
                max_tokens=2000
            )
            # Test the connection
            test_response = llm("Hello")
            logger.info("✓ OpenAI API connected successfully")
            return llm
        except Exception as e:
            logger.warning(f"OpenAI API failed: {e}")
            logger.info("Falling back to mock LLM for demonstration")
            return MockLLM("OpenAI-Mock")
    else:
        logger.info("No OpenAI API key found, using mock LLM for demonstration")
        return MockLLM("Demo-LLM")


def save_research_data(filename: str, content: str) -> str:
    """Save research data to file"""
    try:
        output_dir = Path("research_output")
        output_dir.mkdir(exist_ok=True)
        
        filepath = output_dir / filename
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✓ Saved research data to {filepath}")
        return f"Successfully saved to {filepath}"
    except Exception as e:
        print(f"Failed to save file: {e}")
        return f"Error saving file: {e}"


def load_research_data(filename: str) -> str:
    """Load research data from file"""
    try:
        filepath = Path("research_output") / filename
        if filepath.exists():
            with open(filepath, 'r', encoding='utf-8') as f:
                content = f.read()
            print(f"✓ Loaded research data from {filepath}")
            return content
        else:
            return f"File {filename} not found"
    except Exception as e:
        print(f"Failed to load file: {e}")
        return f"Error loading file: {e}"


def search_web(query: str) -> str:
    """Mock web search tool (replace with real implementation)"""
    import random
    print(f"🔍 Searching web for: {query}")
    
    # Generate mock results dynamically
    categories = [
        "Scientific Journal Articles",
        "Government Reports",
        "Expert Analysis",
        "Technical Blogs",
        "News Articles"
    ]
    
    results = "\n".join(
        f"{i + 1}. {category} ({random.randint(5, 20)} results)\n"
        f"   - Example content related to '{query}'\n"
        f"   - Additional details and insights"
        for i, category in enumerate(random.sample(categories, 3))
    )
    
    return f"""Web Search Results for: "{query}"\n\n{results}\n\nNote: This is a mock search. In production, integrate with real search APIs like Google Scholar, PubMed, etc."""
class ResearchPlatform:
    """Main research platform orchestrator"""
    
    def __init__(self):
        self.llm = setup_llm()
        self.setup_agents()
        self.setup_workflows()
        
    def setup_agents(self):
        """Create specialized research agents"""
        
        # Primary Research Agent
        self.researcher = Agent(
            agent_name="Senior Researcher",
            agent_description="Expert research specialist focused on gathering and analyzing information",
            llm=self.llm,
            system_prompt="""You are a Senior Research Specialist with expertise in conducting comprehensive research across multiple domains. 

Your responsibilities:
- Gather information from multiple authoritative sources
- Identify key themes and patterns in research topics
- Provide structured, well-cited research findings
- Ensure accuracy and reliability of information

Always:
- Use clear, professional language
- Cite sources when possible
- Structure your findings logically
- Highlight key insights and implications""",
            max_loops=1,
            autosave=True,
            verbose=True,
            tools=[]  # Tools were removed due to compatibility issues with the current LLM setup, which caused unexpected behavior during task execution. 
                       # Future developers can reintroduce tools by ensuring compatibility with the LLM and testing for stability. Example:
                       # tools=[ToolAgent(name="WebScraper", description="Scrapes data from the web", function=web_scraper_function)]
        )
        
        # Fact-Checking Agent
        self.fact_checker = Agent(
            agent_name="Fact Checker",
            agent_description="Specialist in verifying information accuracy and reliability",
            llm=self.llm,
            system_prompt="""You are a meticulous Fact-Checking Specialist responsible for verifying the accuracy and reliability of research findings.

Your responsibilities:
- Cross-reference claims with authoritative sources
- Identify potential biases or limitations in research
- Assess the credibility of sources and methodologies
- Flag any inconsistencies or questionable information

Evaluation criteria:
- Source credibility and authority
- Methodology soundness
- Data quality and sample sizes
- Peer review status
- Replication and consensus

Provide confidence ratings and detailed justifications for your assessments.""",
            max_loops=1,
            autosave=True,
            verbose=True,
            tools=[]  # Remove tools for now to avoid issues
        )
        
        # Analysis Agent  
        self.analyst = Agent(
            agent_name="Data Analyst",
            agent_description="Expert in analyzing patterns, trends, and drawing insights from research data",
            llm=self.llm,
            system_prompt="""You are a Senior Data Analyst specializing in extracting meaningful insights from research data and findings.

Your responsibilities:
- Identify patterns and trends in research findings
- Perform comparative analysis across different sources
- Generate actionable insights and recommendations
- Quantify impacts and implications where possible

Analysis framework:
- What: Key findings and observations
- Why: Underlying causes and mechanisms  
- How: Practical implications and applications
- When: Timeline and temporal patterns
- Where: Geographic or contextual variations

Present your analysis with clear visualizations (described), metrics, and strategic recommendations.""",
            max_loops=1,
            autosave=True, 
            verbose=True,
            tools=[]  # Remove tools for now to avoid issues
        )
        
        # Report Writer Agent
        self.writer = Agent(
            agent_name="Report Writer",
            agent_description="Professional writer specializing in creating comprehensive research reports",
            llm=self.llm,
            system_prompt="""You are a Professional Report Writer who creates clear, comprehensive, and engaging research reports for diverse audiences.

Your responsibilities:
- Synthesize complex research into accessible reports
- Structure information logically with clear sections
- Create executive summaries for key stakeholders
- Ensure reports are actionable and well-formatted

Report structure:
1. Executive Summary (key findings & recommendations)
2. Introduction & Methodology
3. Detailed Findings (with evidence)
4. Analysis & Implications
5. Recommendations & Next Steps
6. Appendices (sources, data, etc.)

Writing principles:
- Clarity over complexity
- Evidence-based conclusions
- Actionable recommendations
- Professional tone
- Logical flow""",
            max_loops=1,
            autosave=True,
            verbose=True,
            tools=[]  # Remove tools for now to avoid issues
        )
        
        logger.info("✓ Research agents initialized successfully")
    
    def setup_workflows(self):
        """Setup different workflow patterns"""
        
        # Sequential Research Pipeline
        self.sequential_workflow = SequentialWorkflow(
            name="Research Pipeline",
            description="Sequential research process with specialized agents"
        )
        
        # Parallel Analysis Workflow  
        self.concurrent_workflow = ConcurrentWorkflow(
            max_workers=3
        )
        
        # Agent Network for Complex Tasks
        self.swarm_network = SwarmNetwork(
            name="Research Swarm",
            description="Network of research agents for complex analysis",
            agents=[self.researcher, self.fact_checker, self.analyst, self.writer]
        )
        
        logger.info("✓ Workflows configured successfully")
    
    def run_sequential_research(self, topic: str) -> Dict[str, Any]:
        """Run a complete research process sequentially"""
        logger.info(f"🔬 Starting sequential research on: {topic}")
        
        results = {}
        
        try:
            # Step 1: Primary Research
            logger.info("Step 1: Conducting primary research...")
            research_prompt = f"""Conduct comprehensive research on the topic: "{topic}"

Please provide:
1. Background and context
2. Current state of knowledge  
3. Key findings from recent studies
4. Important statistics and data points
5. Notable experts and their perspectives
6. Emerging trends and developments

Save your findings to 'primary_research.md' for further analysis."""

            research_results = self.researcher.run(research_prompt)
            results['primary_research'] = research_results
            
            # Step 2: Fact Checking
            logger.info("Step 2: Fact-checking research findings...")
            fact_check_prompt = f"""Review and fact-check the research findings on "{topic}".

Load the primary research data and verify:
1. Accuracy of claims and statistics
2. Credibility of cited sources
3. Currency of information (recency)
4. Potential biases or limitations
5. Areas requiring additional verification

Provide a detailed fact-check report with confidence ratings."""

            fact_check_results = self.fact_checker.run(fact_check_prompt)
            results['fact_check'] = fact_check_results
            
            # Step 3: Analysis
            logger.info("Step 3: Analyzing patterns and insights...")
            analysis_prompt = f"""Analyze the verified research findings on "{topic}".

Conduct deep analysis including:
1. Pattern identification and trend analysis
2. Comparative assessment of different perspectives
3. Impact analysis (economic, social, environmental)
4. Risk assessment and opportunity identification  
5. Strategic implications and recommendations

Save your analysis to 'detailed_analysis.md'."""

            analysis_results = self.analyst.run(analysis_prompt)  
            results['analysis'] = analysis_results
            
            # Step 4: Report Generation
            logger.info("Step 4: Creating comprehensive report...")
            report_prompt = f"""Create a comprehensive research report on "{topic}".

Using all previous research, fact-checking, and analysis, create:
1. Executive Summary (2-3 paragraphs)
2. Detailed findings with supporting evidence
3. Key insights and implications
4. Strategic recommendations
5. Implementation roadmap
6. Risk mitigation strategies

Format as a professional report and save to 'final_report.md'."""

            report_results = self.writer.run(report_prompt)
            results['final_report'] = report_results
            
            logger.info("✓ Sequential research pipeline completed successfully")
            
        except Exception as e:
            logger.error(f"Error in sequential research: {e}")
            results['error'] = str(e)
        
        return results
    
    def run_parallel_analysis(self, topic: str) -> Dict[str, Any]:
        """Run parallel analysis with multiple agents"""
        logger.info(f"⚡ Starting parallel analysis on: {topic}")
        
        try:
            # Create concurrent tasks
            tasks = []
            
            # Task 1: Technical Analysis
            tech_task = Task(
                agent=self.analyst,
                description=f"Perform technical analysis of {topic} including data trends, methodologies, and quantitative insights"
            )
            tasks.append(tech_task)
            
            # Task 2: Risk Assessment  
            risk_task = Task(
                agent=self.fact_checker,
                description=f"Conduct comprehensive risk assessment for {topic} including potential challenges, limitations, and mitigation strategies"
            )
            tasks.append(risk_task)
            
            # Task 3: Strategic Overview
            strategy_task = Task(
                agent=self.writer,
                description=f"Create strategic overview of {topic} including opportunities, recommendations, and implementation considerations"
            )
            tasks.append(strategy_task)
            
            # Run tasks concurrently
            self.concurrent_workflow.add(tasks=tasks)
            results = self.concurrent_workflow.run()
            
            logger.info("✓ Parallel analysis completed successfully")
            return {
                'technical_analysis': results[0] if results else "No results",
                'risk_assessment': results[1] if len(results) > 1 else "No results", 
                'strategic_overview': results[2] if len(results) > 2 else "No results"
            }
            
        except Exception as e:
            logger.error(f"Error in parallel analysis: {e}")
            return {'error': str(e)}
    
    def run_swarm_analysis(self, topic: str) -> Dict[str, Any]:
        """Run analysis using swarm network"""
        logger.info(f"🌐 Starting swarm analysis on: {topic}")
        
        try:
            # Run distributed analysis across the swarm
            swarm_prompt = f"""Collaborate as a research team to analyze: "{topic}"

Each agent should contribute their expertise:
- Researcher: Gather comprehensive information
- Fact-Checker: Verify accuracy and reliability  
- Analyst: Extract insights and patterns
- Writer: Synthesize findings into actionable report

Coordinate your efforts to produce a high-quality, multi-perspective analysis."""

            results = self.swarm_network.run_many_agents(swarm_prompt)
            
            logger.info("✓ Swarm analysis completed successfully")
            return {'swarm_results': results}
            
        except Exception as e:
            logger.error(f"Error in swarm analysis: {e}")
            return {'error': str(e)}


def print_banner():
    """Print demo banner"""
    banner = """
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║            🤖 AI RESEARCH & ANALYSIS PLATFORM 🤖            ║
║                                                              ║
║                   Powered by Swarms Framework               ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝

This demo showcases the full capabilities of the Swarms framework:
• Multi-agent collaboration and specialization
• Sequential and concurrent workflow orchestration  
• Intelligent tool usage and file operations
• Robust error handling and fallback mechanisms
• Interactive user experience

"""
    print(banner)


def print_menu():
    """Print interactive menu"""
    menu = """
┌─────────────────────────────────────────────────────────────┐
│                        DEMO MENU                            │
├─────────────────────────────────────────────────────────────┤
│ 1. Sequential Research Pipeline                             │
│    → Complete research process with agent handoffs         │
│                                                             │
│ 2. Parallel Analysis Workshop                              │
│    → Concurrent analysis by specialized agents             │
│                                                             │
│ 3. Swarm Network Analysis                                   │
│    → Distributed intelligence across agent network         │
│                                                             │
│ 4. View Research Output Files                              │
│    → Browse generated reports and data                     │
│                                                             │
│ 5. Run All Workflows (Comprehensive Demo)                  │
│    → Execute all workflow types for comparison             │
│                                                             │
│ 0. Exit                                                     │
└─────────────────────────────────────────────────────────────┘
"""
    print(menu)


def print_results(results: Dict[str, Any], title: str):
    """Print formatted results"""
    print(f"\n{'='*60}")
    print(f"📊 {title}")
    print('='*60)
    
    for key, value in results.items():
        if key != 'error':
            print(f"\n🔸 {key.upper().replace('_', ' ')}:")
            print("-" * 40)
            if isinstance(value, str):
                print(value[:500] + "..." if len(value) > 500 else value)
            else:
                print(str(value)[:500] + "..." if len(str(value)) > 500 else str(value))
    
    if 'error' in results:
        print(f"\n❌ ERROR: {results['error']}")


def view_output_files():
    """View generated research files"""
    output_dir = Path("research_output")
    
    if not output_dir.exists():
        print("\n📁 No research output directory found. Run some analyses first!")
        return
    
    files = list(output_dir.glob("*.md")) + list(output_dir.glob("*.txt"))
    
    if not files:
        print("\n📁 No research files found in output directory.")
        return
    
    print(f"\n📁 Found {len(files)} research files:")
    
    for i, file in enumerate(files, 1):
        print(f"{i}. {file.name}")
    
    try:
        choice = input("\nEnter file number to view (or 0 to return): ")
        choice = int(choice)
        
        if choice == 0:
            return
        elif 1 <= choice <= len(files):
            file_path = files[choice - 1]
            print(f"\n📄 Contents of {file_path.name}:")
            print("=" * 60)
            
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
                print(content)
            
            print("=" * 60)
        else:
            print("❌ Invalid file number")
            
    except (ValueError, FileNotFoundError) as e:
        print(f"❌ Error: {e}")


def main():
    """Main interactive demo function"""
    print_banner()
    
    # Initialize platform
    print("🚀 Initializing AI Research Platform...")
    try:
        platform = ResearchPlatform()
        print("✅ Platform initialized successfully!\n")
    except Exception as e:
        print(f"❌ Failed to initialize platform: {e}")
        sys.exit(1)
    
    while True:
        print_menu()
        
        try:
            choice = input("Enter your choice (0-5): ").strip()
            
            if choice == '0':
                print("\n👋 Thank you for using the AI Research Platform!")
                print("🌟 This demo showcased the power of Swarms framework for multi-agent AI systems.")
                break
            
            elif choice in ['1', '2', '3', '5']:
                topic = input("\n🔍 Enter research topic: ").strip()
                
                if not topic:
                    print("❌ Please enter a valid research topic.")
                    continue
                
                print(f"\n🎯 Research Topic: {topic}")
                print("⏳ Processing... (this may take a moment)")
                
                if choice == '1':
                    results = platform.run_sequential_research(topic)
                    print_results(results, "SEQUENTIAL RESEARCH PIPELINE RESULTS")
                
                elif choice == '2':
                    results = platform.run_parallel_analysis(topic)
                    print_results(results, "PARALLEL ANALYSIS RESULTS")
                
                elif choice == '3':
                    results = platform.run_swarm_analysis(topic)
                    print_results(results, "SWARM NETWORK ANALYSIS RESULTS")
                
                elif choice == '5':
                    print("\n🚀 Running comprehensive analysis with all workflows...")
                    
                    # Sequential
                    print("\n1️⃣ Sequential Pipeline...")
                    seq_results = platform.run_sequential_research(topic)
                    
                    # Parallel
                    print("\n2️⃣ Parallel Analysis...")
                    par_results = platform.run_parallel_analysis(topic)
                    
                    # Swarm
                    print("\n3️⃣ Swarm Network...")
                    swarm_results = platform.run_swarm_analysis(topic)
                    
                    # Summary
                    print("\n" + "="*80)
                    print("📈 COMPREHENSIVE ANALYSIS COMPLETE")
                    print("="*80)
                    print(f"✅ Sequential Pipeline: {'Success' if 'error' not in seq_results else 'Failed'}")
                    print(f"✅ Parallel Analysis: {'Success' if 'error' not in par_results else 'Failed'}")
                    print(f"✅ Swarm Network: {'Success' if 'error' not in swarm_results else 'Failed'}")
                    print("\n💡 Check the research_output/ directory for generated files!")
            
            elif choice == '4':
                view_output_files()
            
            else:
                print("❌ Invalid choice. Please select 0-5.")
        
        except KeyboardInterrupt:
            print("\n\n👋 Demo interrupted by user. Goodbye!")
            break
        except Exception as e:
            print(f"\n❌ An error occurred: {e}")
            logger.error(f"Demo error: {e}")


if __name__ == "__main__":
    main()